# Generated by Django 2.0.1 on 2018-01-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilibiliapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default=1111),
            preserve_default=False,
        ),
    ]
