# Generated by Django 2.0.1 on 2018-01-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilibiliapp', '0002_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField('date published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='modified_time',
            field=models.DateTimeField('date published'),
            preserve_default=False,
        ),
    ]
