# Generated by Django 2.0.1 on 2018-01-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilibiliapp', '0003_auto_20180111_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='modified_time',
            field=models.DateTimeField(),
        ),
    ]
