# Generated by Django 2.0.1 on 2018-01-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilibiliapp', '0004_auto_20180111_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilibiliApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_id', models.IntegerField()),
                ('img_url', models.CharField(max_length=1000)),
                ('start_time', models.CharField(max_length=100)),
                ('end_time', models.CharField(max_length=100)),
            ],
        ),
    ]
